/** Common fabric / material labels for apparel and home textiles (quick-pick in forms). */
export const COMMON_FABRIC_PRESETS = [
  "100% cotton",
  "Cotton blend",
  "Mul cotton / mulmul",
  "Georgette",
  "Chiffon",
  "Organza",
  "Pure silk",
  "Art silk",
  "Linen",
  "Rayon / viscose",
  "Polyester",
  "Velvet",
  "Crepe",
  "Denim",
  "Wool",
  "Khadi",
  "Net / mesh",
  "Satin",
  "Jacquard",
  "Brocade",
  "Lycra / spandex blend",
  "Cotton silk",
  "Tussar silk",
  "Handloom cotton",
] as const;
