import type { SuperCategory } from "@/lib/title-pipeline";

/** Searchable category labels grouped by super-category (Idea 4 spec). */
export const CATEGORY_GROUPS: Record<SuperCategory, string[]> = {
  clothing: [
    "Saree",
    "Kurti",
    "Lehenga",
    "Salwar Suit",
    "Dupatta",
    "Kurta",
    "Shirt",
    "T-Shirt",
    "Jeans",
    "Trousers",
    "Jacket",
    "Sweater",
    "Dress",
    "Skirt",
    "Blouse",
    "Lingerie",
    "Nightwear",
    "Kids Clothing",
    "Ethnic Wear",
    "Western Wear",
  ],
  electronics: [
    "Mobile Phone",
    "Laptop",
    "Tablet",
    "Headphones",
    "Earphones",
    "Speaker",
    "Smartwatch",
    "Camera",
    "Charger",
    "Power Bank",
    "Keyboard",
    "Mouse",
    "Monitor",
    "TV",
    "Refrigerator",
    "Washing Machine",
    "AC",
    "Mixer Grinder",
    "Microwave",
  ],
  beauty: [
    "Face Cream",
    "Serum",
    "Sunscreen",
    "Lipstick",
    "Foundation",
    "Mascara",
    "Kajal",
    "Shampoo",
    "Conditioner",
    "Hair Oil",
    "Face Wash",
    "Perfume",
    "Deodorant",
    "Nail Polish",
    "Body Lotion",
    "Face Mask",
    "Eye Cream",
  ],
  footwear: [
    "Sneakers",
    "Sandals",
    "Slippers",
    "Heels",
    "Boots",
    "Loafers",
    "Sports Shoes",
    "Formal Shoes",
    "Flip Flops",
    "Kolhapuri",
  ],
  bags: [
    "Handbag",
    "Backpack",
    "Clutch",
    "Wallet",
    "Tote Bag",
    "Sling Bag",
    "Laptop Bag",
    "Travel Bag",
    "School Bag",
  ],
  jewellery: [
    "Necklace",
    "Earrings",
    "Bracelet",
    "Ring",
    "Bangles",
    "Anklet",
    "Pendant",
    "Mangalsutra",
    "Maang Tikka",
  ],
  home: [
    "Sofa",
    "Bed",
    "Table",
    "Chair",
    "Wardrobe",
    "Curtains",
    "Bedsheet",
    "Pillow",
    "Mattress",
    "Lamp",
    "Clock",
    "Wall Art",
    "Kitchen Utensils",
    "Cookware",
  ],
  food: [
    "Snacks",
    "Dry Fruits",
    "Spices",
    "Masala",
    "Pickle",
    "Tea",
    "Coffee",
    "Biscuits",
    "Sweets",
    "Namkeen",
    "Organic Food",
  ],
  health: [
    "Protein Powder",
    "Vitamins",
    "Supplements",
    "Ayurvedic",
    "Fitness Equipment",
    "Yoga Mat",
    "Medical Device",
  ],
  kids: ["Toys", "Board Games", "Educational Toys", "Baby Clothes", "Soft Toys", "Cycles", "Stationery"],
  stationery: ["Pen", "Notebook", "Diary", "Pencil", "Eraser", "Markers", "Files", "Desk Organizer"],
  pets: ["Pet Food", "Dog Collar", "Cat Litter", "Aquarium", "Bird Feed"],
  general: ["Other"],
};

export const FIELDS_BY_CATEGORY: Record<SuperCategory, string[]> = {
  clothing: ["colors", "sizes", "fabric", "occasion"],
  electronics: ["specs", "weight", "dimensions"],
  beauty: ["ingredients", "weight"],
  footwear: ["colors", "sizes", "occasion"],
  bags: ["colors", "dimensions"],
  jewellery: ["colors", "occasion", "weight"],
  home: ["colors", "dimensions", "weight"],
  food: ["ingredients", "weight"],
  health: ["ingredients", "weight"],
  kids: ["colors", "sizes"],
  stationery: ["colors"],
  pets: ["weight", "dimensions"],
  general: ["colors"],
};

export function allCategoryOptions(): { label: string; group: SuperCategory }[] {
  const out: { label: string; group: SuperCategory }[] = [];
  for (const [group, labels] of Object.entries(CATEGORY_GROUPS) as [SuperCategory, string[]][]) {
    for (const label of labels) {
      out.push({ label, group });
    }
  }
  return out.sort((a, b) => a.label.localeCompare(b.label));
}

/** Display-friendly labels for each super-category. */
export const SUPER_CATEGORY_LABELS: Record<SuperCategory, string> = {
  clothing: "Clothing",
  electronics: "Electronics",
  beauty: "Beauty",
  footwear: "Footwear",
  bags: "Bags",
  jewellery: "Jewellery",
  home: "Home",
  food: "Food",
  health: "Health",
  kids: "Kids",
  stationery: "Stationery",
  pets: "Pets",
  general: "General",
};

/** Order to show category groups in the dropdown. */
export const SUPER_CATEGORY_ORDER: SuperCategory[] = [
  "clothing",
  "electronics",
  "beauty",
  "footwear",
  "bags",
  "jewellery",
  "home",
  "food",
  "health",
  "kids",
  "stationery",
  "pets",
  "general",
];
